CREATE TABLE categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	parentId INTEGER NOT NULL DEFAULT (0),
	type INTEGER NOT NULL DEFAULT (0),
	name TEXT NOT NULL
);
CREATE TABLE transactions (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	date TEXT NOT NULL,
	type INTEGER NOT NULL DEFAULT (0),
	catId INTEGER NOT NULL DEFAULT (0),
	value REAL NOT NULL DEFAULT (0),
	desc TEXT NOT NULL,
	contractor TEXT NOT NULL
);
